# Generated by Django 4.2 on 2024-01-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Работа'},
        ),
    ]
